import { galleryMainType } from "@/types/Gallery/gallery";

export const GALLERY_MAIN: galleryMainType = [
  {
    type: "PLYWANIE",
    title: "NAUKA PŁYWANIA Z RODZICAMI",
    coverImage: "nauka-plywania-z-rodzicami.webp",
    stripColor: "darkBlue",
    stripTextColor: "white",
    href: "naukaplywaniazrodzicami",
    images: {
      landscapes: [["01", ""]],
      portraits: ["01", "02", "03", "04", "05"],
    },
  },
  {
    type: "PLYWANIE",
    title: "NAUKA PŁYWANIA DZIECI I MŁODZIEŻ",
    coverImage: "nauka-plywania-dzieci-i-mlodziez.webp",
    stripColor: "darkBlue",
    stripTextColor: "white",
    href: "naukaplywaniadzieciimlodziez",
    images: {
      landscapes: [
        ["01", "02"],
        ["03", "04"],
        ["05", "06"],
        ["07", ""],
      ],
      portraits: [
        "01",
        "02",
        "03",
        "04",
        "05",
        "06",
        "07",
        "08",
        "09",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "22",
        "23",
      ],
    },
  },
  {
    type: "ZIMA",
    title: "WYJAZD NA NARTY 2024",
    coverImage: "wyjazd-na-narty-2024.webp",
    stripColor: "white",
    stripTextColor: "darkBlue",
    href: "wyjazdnanarty2024",
    images: {
      landscapes: [["01", "02"]],
      portraits: [
        "01",
        "02",
        "03",
        "04",
        "05",
        "06",
        "07",
        "08",
        "09",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
      ],
    },
  },
  {
    type: "PLYWANIE",
    title: "NAUKA PŁYWANIA DOROŚLI",
    coverImage: "nauka-plywania-dorosli.png",
    stripColor: "darkBlue",
    stripTextColor: "white",
    href: "naukaplywaniadorosli",
    images: { landscapes: [], portraits: [] },
  },
  {
    type: "LATO",
    title: "OBÓZ LETNI",
    coverImage: "obozy-letnie.png",
    stripColor: "basicGreen",
    stripTextColor: "white",
    href: "obozletni",
    images: { landscapes: [], portraits: [] },
  },
  {
    type: "LATO",
    title: "PÓŁKOLONIA LATO",
    coverImage: "polkolonie-letnie.png",
    stripColor: "basicGreen",
    stripTextColor: "white",
    href: "polkolonialato",
    images: { landscapes: [], portraits: [] },
  },
  {
    type: "ZIMA",
    title: "OBÓZ ZIMOWY",
    coverImage: "obozy-zimowe.png",
    stripColor: "white",
    stripTextColor: "darkBlue",
    href: "obozzimowy",
    images: { landscapes: [], portraits: [] },
  },
  {
    type: "ZIMA",
    title: "PÓŁKOLONIA ZIMA",
    coverImage: "polkolonie-zimowe.png",
    stripColor: "white",
    stripTextColor: "darkBlue",
    href: "polkoloniazima",
    images: { landscapes: [], portraits: [] },
  },
];
