import { galleryMainType } from "@/types/Gallery/gallery";

export const GALLERY_MAIN: galleryMainType = [
  {
    type: "PLYWANIE",
    title: "NAUKA PŁYWANIA Z RODZICAMI",
    coverImage: "nauka-plywania-z-rodzicami.webp",
    stripColor: "darkBlue",
    stripTextColor: "white",
    href: "naukaplywaniazrodzicami",
    images: {
      landscapes: [["01", ""]],
      portraits: ["01", "02", "03", "04", "05"],
    },
  },
  {
    type: "PLYWANIE",
    title: "NAUKA PŁYWANIA DZIECI I MŁODZIEŻ",
    coverImage: "nauka-plywania-dzieci-i-mlodziez.webp",
    stripColor: "darkBlue",
    stripTextColor: "white",
    href: "naukaplywaniadzieciimlodziez",
    images: {
      landscapes: [
        ["01", "02"],
        ["03", "04"],
        ["05", "06"],
        ["07", ""],
      ],
      portraits: [
        "01",
        "02",
        "03",
        "04",
        "05",
        "06",
        "07",
        "08",
        "09",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "22",
        "23",
      ],
    },
  },
  {
    type: "PLYWANIE",
    title: "NAUKA PŁYWANIA DOROŚLI",
    coverImage: "nauka-plywania-dorosli.png",
    stripColor: "darkBlue",
    stripTextColor: "white",
    href: "naukaplywaniadorosli",
    images: { landscapes: [], portraits: [] },
  },
  {
    type: "ZIMA",
    title: "WYJAZD NA NARTY 2024",
    coverImage: "wyjazd-na-narty-2024.webp",
    stripColor: "white",
    stripTextColor: "darkBlue",
    href: "wyjazdnanarty2024",
    images: {
      landscapes: [["01", "02"]],
      portraits: [
        "01",
        "02",
        "03",
        "04",
        "05",
        "06",
        "07",
        "08",
        "09",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
      ],
    },
  },
  {
    type: "LATO",
    title: "BOBOWSKA PRZYGODA",
    coverImage: "bobowska-przygoda.webp",
    stripColor: "basicGreen",
    stripTextColor: "white",
    href: "bobowskaprzygoda",
    images: {
      landscapes: [
        ["01", "02"],
        ["03", "04"],
        ["05", "06"],
      ],
      portraits: [
        "01",
        "02",
        "03",
        "04",
        "05",
        "06",
        "07",
        "08",
        "09",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "22",
        "23",
        "24",
        "25",
        "26",
        "27",
        "28",
        "29",
        "30",
        "31",
        "32",
        "33",
        "34",
      ],
    },
  },
  {
    type: "LATO",
    title: "BOBOWSKA PRZYGODA II",
    coverImage: "bobowska-przygoda-2.webp",
    stripColor: "basicGreen",
    stripTextColor: "white",
    href: "bobowskaprzygoda2",
    images: {
      landscapes: [
        ["01", "02"],
        ["03", "04"],
        ["05", "06"],
      ],
      portraits: [
        "01",
        "02",
        "03",
        "04",
        "05",
        "06",
        "07",
        "08",
        "09",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "22",
        "23",
        "24",
        "25",
        "26",
        "27",
        "28",
        "29",
        "30",
        "31",
      ],
    },
  },
  {
    type: "LATO",
    title: "KREATYWNE LABORATORIUM",
    coverImage: "kreatywne-laboratorium.webp",
    stripColor: "basicGreen",
    stripTextColor: "white",
    href: "kreatywnelaboratorium",
    images: {
      landscapes: [
        ["01", "02"],
        ["03", ""],
      ],
      portraits: [
        "01",
        "02",
        "03",
        "04",
        "05",
        "06",
        "07",
        "08",
        "09",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "22",
        "23",
        "24",
        "25",
        "26",
        "27",
        "28",
        "29",
      ],
    },
  },
  {
    type: "LATO",
    title: "WAKACYJNA FRAJDA",
    coverImage: "wakacyjna-frajda.webp",
    stripColor: "basicGreen",
    stripTextColor: "white",
    href: "wakacyjnafrajda",
    images: {
      landscapes: [
        ["01", "02"],
        ["03", "04"],
      ],
      portraits: [
        "01",
        "02",
        "03",
        "04",
        "05",
        "06",
        "07",
        "08",
        "09",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "22",
        "23",
        "24",
        "25",
        "26",
        "27",
        "28",
        "29",
        "30",
        "31",
        "32",
        "33",
        "34",
      ],
    },
  },
];
