'use client';
import 'react';
import styles from './trainersSection.module.scss';
import AboutTextPoppins from '@/components/Ui/AboutTextPoppins/AboutTextPoppins';
import BackgroundText from '@/components/Ui/BackgroundText/BackgroundText';
import StickerH2 from '@/components/Ui/StickerH2/StickerH2';
import InstructorBubble from '@/components/Globals/InstructorBubble/InstructorBubble';
import LinkButton from '@/components/Ui/Buttons/LinkButton';
import Scrap2 from '@/components/Ui/Scrap/Scrap2';
import {COLORS} from '@/utils/UI/colors';
const TrainersSection: React.FC = () => {
  return (
    <section className={styles.trainers}>
      <BackgroundText title="NASZ ZESPÓŁ" />
      <div className={styles['trainers__about-container']}>
        <StickerH2
          title="DOŚWIADCZENI"
          titleStrip="TRENERZY"
          stripTextColor="basicOrange"
          stripBgColor="white"
          scale={1.2}
          paddingBottom={0}
        />
        <AboutTextPoppins
          title=""
          titleColor="basicOrange"
          description="Nasz zespół to grono doświadczonych instruktorów, którzy od lat z pasją i zaangażowaniem szkolą w zakresie pływania. Każdy z naszych instruktorów to osoba, która osobiście trenowała pływanie i posiada bogate doświadczenie w tej dziedzinie. Dzięki temu możemy zapewnić profesjonalne i rzetelne podejście do każdego uczestnika – wiemy, jak wygląda trening z perspektywy pływaka, i potrafimy skutecznie przekazywać wiedzę oraz technikę."
        />
      </div>
      <div className={styles['trainers__trainers-gallery']}>
        <InstructorBubble
          scale={1}
          img1="instructor-1.png"
          img2="instructor-1.png"
          instructorName=""
          href="/"
        />
        <InstructorBubble
          scale={0.6}
          img1="instructor-1.png"
          img2="instructor-1.png"
          instructorName=""
          href="/"
        />
        <InstructorBubble
          scale={0.8}
          img1="instructor-1.png"
          img2="instructor-1.png"
          instructorName=""
          href="/"
        />
        <InstructorBubble
          scale={0.9}
          img1="instructor-1.png"
          img2="instructor-1.png"
          instructorName=""
          href="/"
        />
        <LinkButton
          title="Nasz zespół"
          textColor="basicOrange"
          bgColor="white"
          href="/naszzespol"
        />
      </div>
      <Scrap2 color="darkBlue" position="bottom" />
      <div
        className={styles.bubbles}
        style={{
          background: `linear-gradient(180deg,${COLORS['darkBlue']} 0%, ${COLORS['darkBlue']} 100%)`,
        }}
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="1921"
          height="416"
          viewBox="0 0 1921 416"
          fill="none"
        >
          <g id="bubble-1">
            <rect
              x="434.742"
              y="249.934"
              width="59"
              height="59"
              rx="29.5"
              stroke="white"
              strokeWidth="2"
            />
            <circle
              cx="484.742"
              cy="271.934"
              r="10"
              fill="white"
              fillOpacity="0.62"
            />
          </g>
          <g id="bubble-2">
            <rect
              x="1443"
              y="102.434"
              width="59"
              height="59"
              rx="29.5"
              stroke="white"
              strokeWidth="2"
            />
            <circle
              cx="1493"
              cy="124.434"
              r="10"
              fill="white"
              fillOpacity="0.62"
            />
          </g>
          <g id="bubble-3">
            <rect
              x="1466"
              y="233.934"
              width="59"
              height="59"
              rx="29.5"
              stroke="white"
              strokeWidth="2"
            />
            <circle
              cx="1516"
              cy="255.934"
              r="10"
              fill="white"
              fillOpacity="0.62"
            />
          </g>
          <g id="bubble-4">
            <rect
              x="1211.5"
              y="99.4336"
              width="59"
              height="59"
              rx="29.5"
              stroke="white"
              strokeWidth="2"
            />
            <circle
              cx="1261.5"
              cy="121.434"
              r="10"
              fill="white"
              fillOpacity="0.62"
            />
          </g>
          <g id="bubble-5">
            <rect
              x="321"
              y="232.434"
              width="72"
              height="72"
              rx="36"
              stroke="white"
              strokeWidth="2"
            />
            <circle
              cx="366.872"
              cy="250.305"
              r="5.87152"
              fill="white"
              fillOpacity="0.62"
            />
          </g>
          <g id="bubble-6">
            <rect
              x="605"
              y="295.434"
              width="77"
              height="76"
              rx="38"
              stroke="white"
              strokeWidth="2"
            />
            <circle
              cx="655"
              cy="317.434"
              r="10"
              fill="white"
              fillOpacity="0.62"
            />
          </g>
          <g id="bubble-7">
            <rect
              x="789.875"
              y="241.434"
              width="77"
              height="76"
              rx="38"
              stroke="white"
              strokeWidth="2"
            />
            <circle
              cx="839.875"
              cy="263.434"
              r="10"
              fill="white"
              fillOpacity="0.62"
            />
          </g>
          <g id="bubble-8">
            <rect
              x="1584"
              y="193.434"
              width="49"
              height="49"
              rx="24.5"
              stroke="white"
              strokeWidth="2"
            />
            <circle
              cx="1599.25"
              cy="208.684"
              r="6.25"
              fill="white"
              fillOpacity="0.62"
            />
          </g>
          <g id="bubble-9">
            <rect
              x="373.742"
              y="106.934"
              width="77"
              height="76"
              rx="38"
              stroke="white"
              strokeWidth="2"
            />
            <circle
              cx="423.742"
              cy="128.934"
              r="10"
              fill="white"
              fillOpacity="0.62"
            />
          </g>
          <g id="bubble-10">
            <rect
              x="757"
              y="132.934"
              width="77"
              height="76"
              rx="38"
              stroke="white"
              strokeWidth="2"
            />
            <circle
              cx="807"
              cy="154.934"
              r="10"
              fill="white"
              fillOpacity="0.62"
            />
          </g>
          <g id="bubble-11">
            <rect
              x="935.5"
              y="106.934"
              width="77"
              height="76"
              rx="38"
              stroke="white"
              strokeWidth="2"
            />
            <circle
              cx="985.5"
              cy="128.934"
              r="10"
              fill="white"
              fillOpacity="0.62"
            />
          </g>
          <g id="bubble-12">
            <rect
              x="1163"
              y="287.434"
              width="77"
              height="76"
              rx="38"
              stroke="white"
              strokeWidth="2"
            />
            <circle
              cx="1213"
              cy="309.434"
              r="10"
              fill="white"
              fillOpacity="0.62"
            />
          </g>
          <g id="bubble-13">
            <rect
              x="935.5"
              y="249.934"
              width="77"
              height="76"
              rx="38"
              stroke="white"
              strokeWidth="2"
            />
            <circle
              cx="985.5"
              cy="271.934"
              r="10"
              fill="white"
              fillOpacity="0.62"
            />
          </g>
          <g id="bubble-14">
            <rect
              x="1042"
              y="54.9336"
              width="77"
              height="76"
              rx="38"
              stroke="white"
              strokeWidth="2"
            />
            <circle
              cx="1092"
              cy="76.9336"
              r="10"
              fill="white"
              fillOpacity="0.62"
            />
          </g>
          <g id="bubble-15">
            <rect
              x="526"
              y="145.934"
              width="77"
              height="76"
              rx="38"
              stroke="white"
              strokeWidth="2"
            />
            <circle
              cx="576"
              cy="167.934"
              r="10"
              fill="white"
              fillOpacity="0.62"
            />
          </g>
          <g id="bubble-16">
            <rect
              x="1600.25"
              y="294.934"
              width="77"
              height="76"
              rx="38"
              stroke="white"
              strokeWidth="2"
            />
            <circle
              cx="1650.25"
              cy="316.934"
              r="10"
              fill="white"
              fillOpacity="0.62"
            />
          </g>
          <g id="bubble-17">
            <rect
              x="1277"
              y="206.434"
              width="77"
              height="76"
              rx="38"
              stroke="white"
              strokeWidth="2"
            />
            <circle
              cx="1327"
              cy="228.434"
              r="10"
              fill="white"
              fillOpacity="0.62"
            />
          </g>
          <g id="bubble-18">
            <rect
              x="143"
              y="97.4336"
              width="59"
              height="58"
              rx="29"
              stroke="white"
              strokeWidth="2"
            />
            <circle
              cx="189.211"
              cy="115.644"
              r="6.21069"
              fill="white"
              fillOpacity="0.62"
            />
          </g>
          <g id="bubble-19">
            <rect
              x="143"
              y="265.434"
              width="61"
              height="59"
              rx="29.5"
              stroke="white"
              strokeWidth="2"
            />
            <circle
              cx="193"
              cy="287.434"
              r="10"
              fill="white"
              fillOpacity="0.62"
            />
          </g>
        </svg>
      </div>
    </section>
  );
};
export default TrainersSection;
